export type WatchlistItem = {
  id: number;
  sourceSymbol: string;
  sortOrder: number;
  starred: boolean;
  name: string;
  code: string;
  market: "沪市" | "深市" | "港股" | "美股";
  price: string;
  changeAmount: string;
  changePercent: string;
  amount: string;
  turnoverRate: string;
  pe: string;
  industry: string;
  tags: string[];
  note: string;
  createdAt?: string;
  updatedAt: string;
  trend: "up" | "down";
  trendPoints?: number[];
};
