import type { AIProviderType, ModelConfig, ModelConfigDraft, ProviderItem, SettingsTabKey } from "./types";

export const settingsTabs: Array<{ key: SettingsTabKey; label: string }> = [
  { key: "basic", label: "基础设置" },
  { key: "model-config", label: "模型配置" },
  { key: "data-source", label: "数据源设置" },
  { key: "proxy", label: "代理设置" },
  { key: "notification", label: "通知设置" },
  { key: "workspace", label: "工作区设置" },
  { key: "cache", label: "缓存管理" },
  { key: "about", label: "关于" },
];

export const providers: ProviderItem[] = [
  { id: "openai-compatible", name: "OpenAI Compatible", icon: "openai", defaultBaseUrl: "https://api.openai.com/v1" },
  { id: "deepseek", name: "DeepSeek", icon: "deepseek", defaultBaseUrl: "https://api.deepseek.com" },
  { id: "qwen", name: "Qwen", icon: "qwen", defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1" },
  { id: "doubao-ark", name: "Doubao / Ark", icon: "doubao", defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3" },
  { id: "gemini", name: "Gemini", icon: "gemini", defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta" },
  { id: "claude", name: "Claude", icon: "claude", defaultBaseUrl: "https://api.anthropic.com/v1" },
  { id: "ollama", name: "Ollama", icon: "ollama", defaultBaseUrl: "http://127.0.0.1:11434/v1" },
  { id: "lm-studio", name: "LM Studio", icon: "lm-studio", defaultBaseUrl: "http://127.0.0.1:1234/v1" },
  { id: "custom-http-provider", name: "Custom HTTP Provider", icon: "llm-api", defaultBaseUrl: "http://10.0.0.10:8000/v1" },
];

export const mockModelConfigs: ModelConfig[] = [
  {
    id: "openai-default",
    name: "默认 OpenAI",
    provider: "openai-compatible",
    providerName: "OpenAI Compatible",
    baseUrl: "https://api.openai.com/v1",
    modelName: "gpt-4o",
    streamEnabled: true,
    isDefault: true,
    keyStatus: { hasKey: true, maskedKey: "sk-****abcd" },
    connectionStatus: "normal",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "openai-compatible",
    name: "OpenAI 兼容",
    provider: "openai-compatible",
    providerName: "OpenAI Compatible",
    baseUrl: "https://api.openai.com/v1",
    modelName: "gpt-4-turbo",
    streamEnabled: true,
    isDefault: false,
    keyStatus: { hasKey: true, maskedKey: "sk-****wxyz" },
    connectionStatus: "normal",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    provider: "openai-compatible",
    providerName: "OpenAI Compatible",
    baseUrl: "https://xxx.openai.azure.com/",
    modelName: "gpt-4o",
    streamEnabled: true,
    isDefault: false,
    keyStatus: { hasKey: true, maskedKey: "sk-****1234" },
    connectionStatus: "normal",
    temperature: 0.6,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "deepseek-chat",
    name: "DeepSeek Chat",
    provider: "deepseek",
    providerName: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    modelName: "deepseek-chat",
    streamEnabled: true,
    isDefault: false,
    keyStatus: { hasKey: true, maskedKey: "sk-****abcd" },
    connectionStatus: "normal",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "deepseek-reasoner",
    name: "DeepSeek Reasoner",
    provider: "deepseek",
    providerName: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    modelName: "deepseek-reasoner",
    streamEnabled: true,
    isDefault: false,
    keyStatus: { hasKey: true, maskedKey: "sk-****efgh" },
    connectionStatus: "untested",
    temperature: 0.5,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "qwen-max",
    name: "Qwen-Max",
    provider: "qwen",
    providerName: "Qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    modelName: "qwen-max",
    streamEnabled: true,
    isDefault: false,
    keyStatus: { hasKey: false },
    connectionStatus: "failed",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "doubao-pro-32k",
    name: "Doubao-pro-32k",
    provider: "doubao-ark",
    providerName: "Doubao / Ark",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    modelName: "doubao-pro-32k",
    streamEnabled: true,
    isDefault: false,
    keyStatus: { hasKey: true, maskedKey: "sk-****abcd" },
    connectionStatus: "normal",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "gemini-15-pro",
    name: "Gemini 1.5 Pro",
    provider: "gemini",
    providerName: "Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    modelName: "gemini-1.5-pro",
    streamEnabled: true,
    isDefault: false,
    keyStatus: { hasKey: false },
    connectionStatus: "untested",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "ollama-local",
    name: "Ollama Local",
    provider: "ollama",
    providerName: "Ollama",
    baseUrl: "http://127.0.0.1:11434/v1",
    modelName: "llama3.1:8b",
    streamEnabled: true,
    isDefault: false,
    keyStatus: { hasKey: false },
    connectionStatus: "untested",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
  {
    id: "custom-local",
    name: "Custom Local",
    provider: "custom-http-provider",
    providerName: "Custom HTTP Provider",
    baseUrl: "http://10.0.0.10:8000/v1",
    modelName: "my-model",
    streamEnabled: false,
    isDefault: false,
    keyStatus: { hasKey: true, maskedKey: "sk-****abcd" },
    connectionStatus: "failed",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
  },
];

export function providerName(provider: AIProviderType) {
  return providers.find((item) => item.id === provider)?.name ?? "OpenAI Compatible";
}

export function defaultDraft(provider: AIProviderType): ModelConfigDraft {
  const item = providers.find((value) => value.id === provider) ?? providers[0];
  return {
    name: "",
    provider: item.id,
    baseUrl: item.defaultBaseUrl,
    modelName: "",
    temperature: 0.7,
    maxTokens: 4096,
    timeoutSeconds: 60,
    streamEnabled: true,
    isDefault: false,
  };
}

export function draftFromConfig(config: ModelConfig): ModelConfigDraft {
  return {
    id: config.id,
    name: config.name,
    provider: config.provider,
    baseUrl: config.baseUrl,
    modelName: config.modelName,
    temperature: config.temperature,
    maxTokens: config.maxTokens,
    timeoutSeconds: config.timeoutSeconds,
    streamEnabled: config.streamEnabled,
    isDefault: config.isDefault,
  };
}
